# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-29 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logindata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=450, unique=True)),
                ('question_id', models.PositiveIntegerField()),
                ('choice1', models.CharField(max_length=450, null=True)),
                ('choice2', models.CharField(max_length=450, null=True)),
                ('choice3', models.CharField(max_length=450, null=True)),
                ('choice4', models.CharField(max_length=450, null=True)),
                ('selectedchoice', models.CharField(max_length=450, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.PositiveIntegerField()),
                ('year_of_study', models.CharField(max_length=100)),
                ('contactno', models.PositiveIntegerField()),
                ('group', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newres.Userdata'),
        ),
    ]
