# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-29 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newres', '0004_auto_20190129_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='group',
            field=models.CharField(default='heloo', max_length=100),
        ),
    ]
